# Site settings
title: The Workbench
description: 'The Workbench as a starting point for interesting journeys.' # this means to ignore newlines until "base-url:"
permalink: ':title:output_ext'
base-url: "/"
url: "https://www.liberit.com" # the base hostname & protocol for your site, e.g. http://example.com
#logo: "/assets/img/branding/MVM-logo-full.svg"
logo: "/assets/img/branding/Workbench logo.png"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Daniel Peters # add your name
author-pic: Myself_Neon_grey.jpg
about-author: 

# Contact links
email: peters.dan@outlook.com # Add your Email address
phone: # Add your Phone number
website: https://www.liberit.com # Add your website
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
bandcamp: # Add your Bandcamp username
stackoverflow: # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Disqus
discus_identifier: # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 1
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]


# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

#DP ------
defaults:
  -
    scope:
        path: ""
    values:
        author: "Daniel Peters"
        layout: post
        lang: nl
        base-url: "/"
  -
    scope:
        path: en
    values:
        lang: en
        base-url: "/en/"

#DP -------------
t:
    about:
        nl: "Over ons"
        en: "About"
        

# Value to use into url per language
langs-value:
    nl: ""
    en: en
#-------

plugins:
  - jekyll-paginate 
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]